package dflabs.io.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMAGE_POST.
 */
public class ImagePost {

    private Long id;
    private String url;
    private Long post_id;

    public ImagePost() {
    }

    public ImagePost(Long id) {
        this.id = id;
    }

    public ImagePost(Long id, String url, Long post_id) {
        this.id = id;
        this.url = url;
        this.post_id = post_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Long getPost_id() {
        return post_id;
    }

    public void setPost_id(Long post_id) {
        this.post_id = post_id;
    }

}
